# User Settings | Edit there as per required

title: Study Notes
url: "http://dgyblog.com/study-notes/"
baseurl: "/study-notes"

# This will show up at the top of index page
site_heading: >
    Study <span class="faded">Notes</span>

email: duguyue100@gmail.com
author: Yuhuang Hu
# This description will show up in google search results
# (for index page) etc.
description: >
    My study notes, powered by accent theme.

# This will what will show against &copy; in the footer
copyright: duguyue100
# Toggle your short bio, which will displayed on your index page
# Just toggle it and run jekyll again to see
intro: false         # Tip: Remove the span from site_heading if intro is set to true
# This will be displayed in your intro
short_bio: >
    Welcome! This is <span>accent</span>, a mobile friendly theme for Jekyll. The main feature of this
    theme is that you can change the accent color. Refer the
    <a class="underline different-highlight" href="http://ankitsultana.me/accent/documentation.html">
        Documentation
    </a>
    to know how.

permalink: /:title.html

# Comments are powered by disqus
comments: false

# keep about_stub roughly 12 words long for best results
# This will show up at the bottom of each post
# Note that about_footer should be true if you want
# to see author information at the bottom of each post
about_stub: >
    Skeptic, Rambler, TV addict, ML protégé, AGI supporter, NOT-DOOMED believer, INI master student.

about_footer: true

twitter_username: duguyue10
github_username: duguyue100
facebook_id: yuhuang.hu.5

favicon: true
favicon_location: "images/favicon.ico"

profile_picture: images/temp.png
paginate: 20
paginate_path: "/page/:num"
# tracking_id:  # GA Tracking ID

# Social Stuff | open graph and twitter cards
og_image: "images/accent.png" # This will show in facebook thumbnails
twitter_image: "http://ankitsultana.me/images/accent.png?1234" # This will show in twitter cards

####################################
####################################
####################################
### Build Settings | Don't Touch ###
####################################
####################################
####################################

markdown: kramdown

kramdown:
  input:          GFM
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  syntax_highlighter:        coderay
  coderay_line_numbers:      nil
  coderay_line_number_start: 1
  coderay_tab_width:         4
  coderay_css:               style
  coderay_wrap:              div

gems:
    - jekyll-paginate

sass:
    style: compressed
    sass_dir: _sass

# Scopes
defaults:
    -
        scope:
            path:   ""
            type:   "pages"
        values:
            layout: "page"
    -
        scope:
            path:   ""
            type:   "posts"
        values:
            layout: "post"

exclude: [vendor] # For travis ci
